# K8s Kustomization - feed-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pet-platform

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: feed-service
  version: v1
